export const types = {
  //Auth Actions//
  LOGIN_START: 'LOGIN_START',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  REGISTER_USER_START: 'REGISTER_USER_START',
  REGISTER_USER_SUCCESS:'REGISTER_USER_SUCCESS',
  REGISTER_USER_FAILURE:'REGISTER_USER_FAILURE',
  GET_USER_INFO_START: 'GET_USER_INFO_START',
  GET_USER_INFO_SUCCESS: 'GET_USER_INFO_SUCCESS',
  GET_USER_INFO_FAILURE: 'GET_USER_INFO_FAILURE',


  // User Actions
  GEN_MAP_START: 'GEN_MAP_START',
  GEN_MAP_SUCCESS: 'GEN_MAP_SUCCESS',
  GEN_MAP_FAILURE: 'GEN_MAP_FAILURE',
  GET_MAPS_START: 'GET_MAPS_START',
  GET_MAPS_SUCCESS: 'GET_MAPS_SUCCESS',
  GET_MAPS_FAILURE: 'GET_MAPS_FAILURE',
  SELECT_MAP_SUCCESS: 'SELECT_MAP_SUCCESS',
  SELECT_MAP_START: 'SELECT_MAP_START',
  SELECT_MAP_FAILURE: 'SELECT_MAP_FAILURE',

  //GAME ACTIONS
  UPDATE_PLAYER_START: 'UPDATE_PLAYER_START',
  UPDATE_PLAYER_SUCCESS:'UPDATE_PLAYER_SUCCESS',
  UPDATE_PLAYER_FAILURE: 'UPDATE_PLAYER_FAILURE',
  UPDATE_MONSTER_START: 'UPDATE_MONSTER_START',
  UPDATE_MONSTER_SUCCESS: 'UPDATE_MONSTER_SUCCESS',
  UPDATE_MONSTER_FAILURE: 'UPDATE_MONSTER_FAILURE',
  UPDATE_GRID_START: 'UPDATE_GRID_START',
  UPDATE_GRID_SUCCESS: 'UPDATE_GRID_SUCCESS',
  UPDATE_GRID_FAILURE: 'UPDATE_GRID_FAILURE',



};


