export const types = {
  //Auth Actions//
  LOGIN_START: 'LOGIN_START',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  REGISTER_USER_START: 'REGISTER_USER_START',
  REGISTER_USER_SUCCESS:'REGISTER_USER_SUCCESS',
  REGISTER_USER_FAILURE:'REGISTER_USER_FAILURE',
  GET_USER_INFO_START: 'GET_USER_INFO_START',
  GET_USER_INFO_SUCCESS: 'GET_USER_INFO_SUCCESS',
  GET_USER_INFO_FAILURE: 'GET_USER_INFO_FAILURE',


  // User Actions
  GEN_MAP_START: 'GEN_MAP_START',
  GEN_MAP_SUCCESS: 'GEN_MAP_SUCCESS',
  GEN_MAP_FAILURE: 'GEN_MAP_FAILURE',
  GET_MAPS_START: 'GET_MAPS_START',
  GET_MAPS_SUCCESS: 'GET_MAPS_SUCCESS',
  GET_MAPS_FAILURE: 'GET_MAPS_FAILURE',

};


